version: '3'

services:
  recently-play:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./src/:/recently-played
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    