apiVersion: batch/v1
kind: CronJob
metadata:
  name: recently-played-updater
spec:
  schedule: "15 9,11,12,20 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: recently-played
            image: nginx:latest
            imagePullPolicy: IfNotPresent
            command:
            - curl
            - -X 
            - POST 
            - http://rec-played:8000/auto-update 
          restartPolicy: OnFailure